# Site settings

title: Jekyll theme example | Hakurojo
tagline: Jekyll theme example
email: hakurojo@fake.com
copyright: Mantra
keywords: open theme, github pages

description: > # this means to ignore newlines until "url:". One indent required.
  Example... tests... how it works...

# the base hostname & protocol for your site
url: "http://xxxxxxxxxxxxx.co"

twitter_username: xxxxxxxxxx
github_username:  xxxxxxxxxx

default_image: /img/opentheme-workflow.png

# Pre-processing

markdown: kramdown
highlighter: pygments
safe: true
permalink: pretty # YYYY/MM/DD/page-title/index.html
lsi: true # Lexical analysis (true) takes longer for higher quality
# sass:
#  style: :compressed

# Exclude from Jekyll processing

exclude: ["vendor", "README.md", "node_modules", "gulpfile.js", "package.json"]

# Lists

tag_items: 20     # Applies to categories and tags lists
recent_items: 10  # Applies to recent posts, apps lists
related_items: 5  # Applies to related posts and apps lists

# Layout

pagebar: true # Show (true) page sidebar menu or hide (false) 
postbar: true # Show (true) post sidebar or hide (false) 

# Features

reading_time: true    # Show est. reading time for posts
facebook: false        # Use facebook features
comments: disqus      # Switch disqus | facebook | none - comments. facebook = true required for facebook comments

# Embeds

disqus_name: xxxxxxxxx            # Your site name at Disqus

youtube_controls: 0               # Turn on=1/off=0 Youtube player features when embedding videos

google_map_zoom: 16               # 1=Global zoom 18=Street Level
google_map_view: satellite        # hybrid | satellite | roadmap
google_map_height: 450            # Default map height. Width adjusts to container.

# API Keys. PLEASE DO NOT USE THESE KEYS. Get your own at links in comments.

google_api_key: "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX" # https://code.google.com/apis/console/
google_analytics_ua: "UA-000000000000000-1" # Google Analytics site specific id
google_cse_id: "XXXXXXXXXXXXXXXXXXXXXX:XXXXXXXXXXX" # Google Custom Search Engine unique id

mapbox: "pk.eyJ1Ijoib3BlbnRoZW1lIiwiYSI6ImNIWC1LTUUifQ.vq4k3nfTeTtDAk7eLCrVAw"

facebook_app: "0000000000000000" # https://developers.facebook.com/

mailchimp_u: "0000000000000000000000000" # Mailchimp u=unique identification
mailchimp_id: "00000000000000000" # Mailchip id

addthis_pubid: "xx-00000000000000000000000" # Get your pubid at https://www.addthis.com/dashboard

pingdom_rum: "000000000000000000000000000" # https://my.pingdom.com/dashboard. Real User experience (speed) monitoring.

uservoice: "xxxxxxxxxxxxxxxxxxxxxxxx"